# Generated by Django 5.0.6 on 2024-07-14 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_Updated_default_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_key',
            field=models.CharField(default='default_profile_image_key', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
