# Generated by Django 5.0.6 on 2024-07-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_created_model_for_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 7, 14, 7, 6, 59, 474027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
